### ISSUE TITLE
Remover dependências manuais e generalizar opções gráficas

### ISSUE THREAD

**Issue by lpirola** [Mutirao/Maloca#1]
- [ ] Implementar menu
- [x] Trocar logo
- [ ] Colocar widget area abaixo do menu
- [x] Trocar cor do tema
- [x] Tornar configurável o projeto
- [x] Criar botão para gera json
- [x] Esconder funcionalidades que não são utilizadas: favoritar evento e timeline de redes sociais
- [x] Avaliar se é o caso publicar o no diretórios de temas oficial do wp #

**Comment by Andreqlp** [comment]
O link do projeto Sobra Cidade das Artes no mapas: http://mapa.cultura.ce.gov.br/projeto/103/ 

Esses dois eventos estão vinculados a esse projeto:
http://mapa.cultura.ce.gov.br/evento/447/
http://mapa.cultura.ce.gov.br/evento/446/

**Comment by Andreqlp** [comment]
![avatar](https://cloud.githubusercontent.com/assets/14170372/18515200/eb810908-7a6a-11e6-96dc-acbe6c357625.png)

**Comment by Andreqlp** [comment]
A cor de base para o site é a **#F15929**

Um exemplo de com deve ficar:

![exemplo](https://cloud.githubusercontent.com/assets/14170372/18563052/7df5770a-7b5c-11e6-9a81-0e7eb346ef1d.jpg)

**Comment by lpirola** [comment]
E as logos abaixo do menu, quais são? Pode colocar aqui tb?

**Comment by Andreqlp** [comment]
Na página principal vai ser essa aqui (coloquei no formato png sem fundo, se precisar em outro formato é só avisar):

![marcas-02](https://cloud.githubusercontent.com/assets/14170372/18587614/4ee22574-7bf9-11e6-8e2b-ae73659e859a.png)

Já na página da programação, que possui um modelo de menu mais estreito, seria essa aqui:

![marcas-03](https://cloud.githubusercontent.com/assets/14170372/18587652/6eecede0-7bf9-11e6-8a11-9d8d73acd703.png)

**Comment by Andreqlp** [comment]
É preciso verificar se o padrão da organização da programação está por horário.

**Comment by Andreqlp** [comment]
Lembrando que o menu inicial tem essas opções:
- Cidade da Artes 
- Programação
- Chamada Pública
- Notícias
- Mapa

**Comment by lpirola** [comment]
@uira 

# Verificações para subir no diretório do wordpress:
- https://make.wordpress.org/themes/handbook/review/required/ - Lista com detalhes das verificações executadas;
- https://wordpress.org/plugins/theme-check/ - Plugin para facilitar o trabalho de correção de normas do wordpress;

**Comment by lpirola** [comment]
http://culturalivre.org/
