### ISSUE TITLE
Customização Menu Principal

### ISSUE THREAD

**Issue by Andreqlp** [Mutirao/Maloca#5]
**Menu principal:**
As referências para cada um dos pontos está descrita abaixo.
- [x] Inserir nova logo no meu (a marca anterior tinha margem, o que deixou a logo pequena)
- [x] Mudar o fundo do bloco superior e inferior para a cor branca.
- [x] Mudar as opções e os links
- [x] Mudar o ícone das opções Cidade das Artes, Chamada Pública e Mapa.
- [x] Transferir logos dos realizadores para o rodapé
- [x] Mudar parte final da barra principal (ou trabalhar uma aplicação da logo ou usar a mesma cor de fundo do cabeçalho)

Parte final da barra principal (sugestões):

![menu -21](https://cloud.githubusercontent.com/assets/14170372/18820294/ad10eace-8372-11e6-90da-7492f10c46ec.jpg)

![menub-21](https://cloud.githubusercontent.com/assets/14170372/18820297/ba6ecede-8372-11e6-86f7-822972fc46e1.jpg)

Logo sem borda:
![logo sem borda](https://cloud.githubusercontent.com/assets/14170372/18684220/c56a9c14-7f49-11e6-9bb7-03ddce38cd62.png)

Imagem de referência das cores do menu:
![ref menu](https://cloud.githubusercontent.com/assets/14170372/18684416/7edbfa80-7f4a-11e6-8a22-c3b4b911a6a1.jpg)

Opções e links do menu principal:
- Cidade das Artes (http://culturalivre.org/cidade-das-artes/)
- Programação (http://culturalivre.org/programacao/)
- Mapa (http://culturalivre.org/mapa/)
- Notícias (http://culturalivre.org/noticias/)
- Chamada Pública (http://culturalivre.org/chamada-publica/)

Ícone da opção "Cidade das Artes" (eles estão brincando de esconde esconde, mas estão ai kkk):
![icone_cidade das artes](https://cloud.githubusercontent.com/assets/14170372/18684433/8e410cb8-7f4a-11e6-8396-001ef393b5c1.png)

Ícone da opção "Mapa"
![icone_mapa](https://cloud.githubusercontent.com/assets/14170372/18684440/9350eee4-7f4a-11e6-8a39-d34b21cb8ad1.png)

Ícone da opção "Chamada Pública"
![icone_chamada publica](https://cloud.githubusercontent.com/assets/14170372/18684453/a092bc18-7f4a-11e6-85bc-0b9903e4d79b.png)

*O ícone da programação permanece o que tinha para atrações e ícone de notícia permanece o mesmo.

Bug do menu:
![bug](https://cloud.githubusercontent.com/assets/14170372/18684460/a6ff0d36-7f4a-11e6-9b0d-ceecc7bc6f16.jpg)

**Comment by Andreqlp** [comment]
e  uma outra customização seria alterar o favicon por este:
![favicon-01](https://cloud.githubusercontent.com/assets/14170372/18694531/3a9f2e5a-7f81-11e6-94c1-f2d933f7ce04.png)

**Comment by lpirola** [comment]
@Andreqlp Isso eh possivel customizar pelo wp

**Comment by Andreqlp** [comment]
Maravilhas

**Comment by Andreqlp** [comment]
Marcas dos realizadores na horizontal para o rodapé da página inicial.

![marcas-01](https://cloud.githubusercontent.com/assets/14170372/18721188/ba90ee1c-8005-11e6-8f95-7a36ffcec20f.png)

**Comment by Andreqlp** [comment]
Marca dos realizadores separadas. Atenção: as marcas devem vir na ordem que indiquei acima.

![marcas separadas-02](https://cloud.githubusercontent.com/assets/14170372/18724070/6c7e3e26-8011-11e6-9425-b5886e597b76.png)
![marcas separadas-03](https://cloud.githubusercontent.com/assets/14170372/18724068/6c73dada-8011-11e6-9bab-a1b2ed43c938.png)
![marcas separadas-04](https://cloud.githubusercontent.com/assets/14170372/18724072/6c859888-8011-11e6-8f8c-e29bc03fdc1f.png)
![marcas separadas-05](https://cloud.githubusercontent.com/assets/14170372/18724071/6c80545e-8011-11e6-87b6-0c67f3b81823.png)
![marcas separadas-06](https://cloud.githubusercontent.com/assets/14170372/18724069/6c7b8690-8011-11e6-82ff-c22333cb0de4.png)

.

**Comment by Andreqlp** [comment]
Mais uma customização :) . Uma das opções do menu responsivo, existe uma barra única onde é preciso substituir o nome por "Cidade das Artes".
![menu reduzido](https://cloud.githubusercontent.com/assets/14170372/18767488/ce512070-80f5-11e6-83cb-654ed1706b73.jpg)

É  preciso customizar novamente esse menu, o alterando o da resolução máxima automaticamente modifica esse aqui?
![menu reduzido 2](https://cloud.githubusercontent.com/assets/14170372/18767509/f185b164-80f5-11e6-8aec-2443d116ad8f.jpg)

**Comment by Andreqlp** [comment]
Adicionar mais um link ao menu principal (versão desktop e mobile).
- Formação ( http://culturalivre.org/formacao )

Ícone:
![icone_formacao-01](https://cloud.githubusercontent.com/assets/14170372/18878286/620cdfd0-84a6-11e6-8068-bbaa20ad4458.png)

Ordem no menu:
- Cidade das Artes
- Programação
- Mapa
- Notícias
- **Formação**
- Chamada Pública

**Comment by Andreqlp** [comment]
Ajustes finais no menu para desktop e mobile:

**No menu desktop:**
- inserir o ícone branco na opção "Formação"
-  mudar a cor da parte final da barra principal. Pode-se trabalhar uma aplicação da logo ou usar a mesma cor de fundo do cabeçalho ao invés do verde está atualmente.
- quando entro diretamente pelo http://cidadedasartes.org.br/# as opções "Cidade das Artes" e "Chamada Pública" escapam do bloco laranja (já testei em dois computadores e aparece do mesmo jeito).

![menug01](https://cloud.githubusercontent.com/assets/14170372/19000687/4d931940-871a-11e6-8665-094a7ea95fd1.jpg)

**No menu mobile:**
- Inserir a marca das opções "Mapa" e "Formação" quando o mouse está em cima da opção.

![menup01](https://cloud.githubusercontent.com/assets/14170372/19000822/f976321a-871a-11e6-9414-e16ddfd19594.jpg)

![menup02](https://cloud.githubusercontent.com/assets/14170372/19000821/f975404e-871a-11e6-8913-92d28e4e10d0.jpg)
