### ISSUE TITLE
Habilitar o Google Analytics

### ISSUE THREAD

**Issue by Andreqlp** [Mutirao/Maloca#6]
**ID de acompanhamento:**
UA-74480066-6

**Acompanhamento de website** (tirei a primeira barrinha do comando script pq não sei como deixar o código visível)

script>

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74480066-6', 'auto');
  ga('send', 'pageview');

/script>

**Implementação PHP**
<?php include_once("analyticstracking.php") ?>

**Comment by lpirola** [comment]
feito com ativação do plugin
